const string1 = "Apple";
const string2 = "Organge";
console.log(string1 === string2);
console.log(string1 !== string2);
const mixedcasestring = "HELLO  WORLD";
console.log(mixedcasestring.toLowerCase() === "hello world");
const num1 = 10;
const num2 = 5;
console.log(num1 === num2);
console.log(num1 !== num2);
console.log(num1 > num2);
console.log(num1 < num2);
console.log(num1 >= num2);
console.log(num1 <= num2);
const condition1 = true;
const condition2 = false;
console.log(condition1 && condition2);
console.log(condition1 || condition2);
const fruits = ["Applle", "Organe", "Banana", "Grapes"];
console.log(fruits.includes("Apple"), ("apple"));
export {};
